"""Builder for the WEEKEND-REDTEAM adversarial artefacts (#137).

Run from the repository root:

    python artifacts/adversarial_e2e/build_matrix.py

Emits DEPENDENCY_MAP.{json,md}, ADVERSARIAL_MATRIX.{json,md} and
BLOCKER_LEDGER.{json,md}. Contains no secrets and no local absolute paths.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
BASELINE_MAIN = "5cac5c44b08e43760888362636cadbf3ffb40f1e"
TASK = "ADVERSARIAL-E2E-VALIDATION-V1"
OWNER_LANE = "WEEKEND-REDTEAM"

# --------------------------------------------------------------------------- #
# Phase A — dependency map
# --------------------------------------------------------------------------- #

DEPENDENCY_MAP = {
    "schema": "cross_asset.adversarial_e2e.dependency_map.v1",
    "task": TASK,
    "owner_lane": OWNER_LANE,
    "baseline_main": BASELINE_MAIN,
    "no_wind_window": True,
    "target_chain": [
        "monitoring provider/input",
        "canonical identity / source mapping",
        "monitoring ingestion / DB",
        "catalog / freshness / data-health",
        "WorkbenchRun lineage",
        "governed factor binding / causal transforms",
        "climate / regime / asset rules",
        "DashboardSnapshotV0",
        "SnapshotStore / history",
        "read-only API",
        "frontend/runtime consumption",
    ],
    "components": [
        {
            "authority": "providers/monitoring.py",
            "role": "provider adapter (FRED public CSV / Yahoo) writing MONITORING-only rows",
            "inputs": "DataRequest(series_ids, start, end)",
            "outputs": "list[Observation] with origin=MONITORING, available_at=capture time",
            "persisted_identity": "series_id + source + source_series_id",
            "time_semantics": "available_at = monitoring capture time (explicitly non-PIT)",
            "failure_semantics": "ProviderError -> _failure(...); no fallback, no formal admission",
            "formal_monitoring_boundary": "MONITORING only; never writes acceptance registry",
            "existing_coverage": "tests/unit/providers, tests/integration/test_fred_monitoring_source_expansion.py",
        },
        {
            "authority": "ingestion/monitoring.py",
            "role": "MonitoringRunner: validate + persist monitoring observations",
            "inputs": "provider rows, request, run_id",
            "outputs": "observations rows, provider_attempts, data_quality_events",
            "persisted_identity": "run provider 'MONITORING:<name>' + row identity",
            "time_semantics": "available_at required; ingested_at = now",
            "failure_semantics": "fail the whole run on identity/origin/available_at violations",
            "formal_monitoring_boundary": "formal_admission_attempted=False always",
            "existing_coverage": "tests/unit/ingestion, tests/integration/test_monitoring_provider_calendar.py",
        },
        {
            "authority": "storage/catalog.py + storage/duckdb.py",
            "role": "series catalog, source mappings, observation persistence",
            "inputs": "config/series.yml, config/sources.yml, observation dicts",
            "outputs": "series_catalog, source_mapping, observations",
            "persisted_identity": "series_id, provider, source_series_id",
            "time_semantics": "available_at / vintage_date / ingested_at",
            "failure_semantics": "idempotent insert; no identity validation at the storage boundary",
            "formal_monitoring_boundary": "sync_series_catalog never writes the acceptance registry",
            "existing_coverage": "tests/unit/storage",
        },
        {
            "authority": "engines/freshness.py + reports/monitoring_health.py",
            "role": "calendar freshness and monitoring read-model health",
            "inputs": "series_calendars.yml, calendars.yml, observations, quality events",
            "outputs": "FreshnessResult(OK/STALE/BLOCKED) and monitoring_data_health rows",
            "persisted_identity": "series_id",
            "time_semantics": "session-lag against market_data_cutoff; no weekday/hour heuristic",
            "failure_semantics": "fail closed to BLOCKED for any missing mapping/coverage",
            "formal_monitoring_boundary": "formal_readiness reported separately; monitoring never implies formal",
            "existing_coverage": "tests/unit/test_calendar_coverage.py, tests/integration/test_monitoring_provider_calendar.py",
        },
        {
            "authority": "operations/workbench_run.py",
            "role": "canonical WorkbenchRun lineage and formal previous-valid selection",
            "inputs": "pipeline payload / explicit run object",
            "outputs": "persisted run JSON under artifacts/workbench/runs",
            "persisted_identity": "run_id + decision_time + source_mode + provenance",
            "time_semantics": "economic decision_time ordering; created_at only breaks ties",
            "failure_semantics": "FIXTURE/SIMULATED can never be formal previous-valid",
            "formal_monitoring_boundary": "formal eligibility requires LIVE + formal_gate provenance",
            "existing_coverage": "tests/unit/operations, tests/unit/test_workbench_cli.py",
        },
        {
            "authority": "decision_support/binding.py + config/decision_support_v2_bindings.yml",
            "role": "lane-aware factor binding governance",
            "inputs": "bindings yml, series.yml, sources.yml, taxonomy",
            "outputs": "FactorBindingRegistry",
            "persisted_identity": "factor_id -> canonical_series_ids",
            "time_semantics": "n/a (config authority)",
            "failure_semantics": "import-time rejection of ungoverned / non-equivalent / wrong-transform bindings",
            "formal_monitoring_boundary": "monitoring BOUND requires exact governed identity; formal independently BLOCKED",
            "existing_coverage": "tests/unit/decision_support/test_binding_governance.py",
        },
        {
            "authority": "decision_support/monitoring_adapter.py",
            "role": "MONITORING DB read-model -> canonical observation pack",
            "inputs": "store, WorkbenchRun, binding registry, calendar configs",
            "outputs": "MonitoringObservationPack",
            "persisted_identity": "series_id + source + source_series_id (re-validated since this task)",
            "time_semantics": "available_at <= decision_time; observation_date <= data_cutoff; one vintage per date",
            "failure_semantics": "identity violation -> series BLOCKED with explicit blockers; never silently consumed",
            "formal_monitoring_boundary": "validate() requires lane=MONITORING, origin=CANONICAL_MONITORING, source_mode=LIVE",
            "existing_coverage": "tests/integration/test_real_snapshot_monitoring_adapter.py, tests/adversarial/test_b1_identity_source.py",
        },
        {
            "authority": "decision_support/producer.py",
            "role": "canonical observations -> DashboardSnapshotV0",
            "inputs": "MonitoringObservationPack + optional previous snapshot",
            "outputs": "DashboardSnapshotV0 (MONITORING lane)",
            "persisted_identity": "snapshot_id = sha256(pack + registry version + taxonomy version + model version)",
            "time_semantics": "economic week id = Monday of data_cutoff; previous must precede by decision_time",
            "failure_semantics": "MonitoringSnapshotBlocked for missing regime axes; SyntheticMovementError for uncaused movement",
            "formal_monitoring_boundary": "lane is MONITORING only; formal_admission_granted always False",
            "existing_coverage": "tests/unit/decision_support/test_real_snapshot.py, tests/adversarial/*",
        },
        {
            "authority": "decision_support/{taxonomy,horizon,climate,regime,asset_rules,weekly}.py",
            "role": "horizon separation, climate, interpretable regime, asset gates, weekly-change surfaces",
            "inputs": "bound subfactor scores, release events, market moves",
            "outputs": "clusters, regime state, asset views, four weekly-change surfaces",
            "persisted_identity": "factor_id / family / horizon",
            "time_semantics": "deadband + dwell hysteresis; de-duplicated economic weeks",
            "failure_semantics": "missing never becomes zero; horizon mixing raises; structural context excluded",
            "formal_monitoring_boundary": "no formal OOS path; no fitted weights",
            "existing_coverage": "tests/unit/decision_support/*",
        },
        {
            "authority": "decision_support/serving.py",
            "role": "SnapshotStore + read-only HTTP API",
            "inputs": "root directory of snapshot JSON files",
            "outputs": "latest/by-id/factors/asset/data-health/health payloads",
            "persisted_identity": "snapshot_id filename + latest.json pointer",
            "time_semantics": "no monotonicity guard on latest.json (recorded blocker)",
            "failure_semantics": "FileNotFoundError/ValueError -> 404; corrupt payload surfaces as 404 with internal text",
            "formal_monitoring_boundary": "read-only; no write routes; loopback default",
            "existing_coverage": "tests/unit/decision_support/test_real_snapshot.py, tests/adversarial/test_b6_snapshot_api.py",
            "adjacent_wip_owner": "PR #135 (DECISION-HISTORY-V1)",
        },
        {
            "authority": "frontend/src/snapshot/loader.js + App.jsx",
            "role": "API-first consumption with explicit demo/test mode",
            "inputs": "/api/snapshot/latest",
            "outputs": "adapted view model",
            "persisted_identity": "metadata.snapshot_id",
            "time_semantics": "as_of/decision_time displayed, never recomputed",
            "failure_semantics": "fail visibly; never substitute a golden/demo fixture for a failed API",
            "formal_monitoring_boundary": "lane badge from producer; no client-side economics",
            "existing_coverage": "frontend/tests",
            "adjacent_wip_owner": "PR #136 (Windows runtime), #134",
        },
    ],
    "adjacent_wip_boundaries": [
        {"pr": 135, "issue": 133, "title": "DECISION-HISTORY-V1", "files": ["src/cross_asset/decision_support/decision_history.py", "src/cross_asset/decision_support/serving.py", "src/cross_asset/decision_support/snapshot_cli.py"], "rule": "do not edit; serving.py blockers are owned here"},
        {"pr": 132, "issue": 131, "title": "weekly semantic comparability hardening", "files": ["src/cross_asset/research/weekly_core.py", "tests/unit/test_weekly_*.py"], "rule": "do not edit; record gap only"},
        {"pr": 136, "issue": 134, "title": "Windows REAL-runtime launcher", "files": ["launcher/**", "START_MACRO_WORKBENCH.cmd", "STOP_MACRO_WORKBENCH.cmd"], "rule": "native process semantics are EXTERNAL_EVIDENCE; not exercised here"},
    ],
    "hard_environment_assumption": {
        "wind_available": False,
        "windpy_available": False,
        "proprietary_local_files": False,
        "consequence": "Wind/manual-only cells are NOT_EXERCISED or BLOCKED; never waited for or bypassed",
    },
}

# --------------------------------------------------------------------------- #
# Phase B — adversarial matrix
# --------------------------------------------------------------------------- #

B1 = "B1_identity_source"
B2 = "B2_time_causality"
B3 = "B3_freshness_calendar"
B4 = "B4_factor_regime"
B5 = "B5_asset_rules"
B6 = "B6_snapshot_history_api"
B7 = "B7_weekly_comparability_lane"
B8 = "B8_runtime_launcher"
P2 = "PASS2_emergent_cross_layer"

T_B1 = "tests/adversarial/test_b1_identity_source.py"
T_B2 = "tests/adversarial/test_b2_time_causality.py"
T_B3 = "tests/adversarial/test_b3_freshness_calendar.py"
T_B4 = "tests/adversarial/test_b4_factor_regime.py"
T_B5 = "tests/adversarial/test_b5_asset_rules.py"
T_B6 = "tests/adversarial/test_b6_snapshot_api.py"
T_B7 = "tests/adversarial/test_b7_weekly_lane.py"
T_B8 = "tests/adversarial/test_b8_runtime_boundary.py"
T_C2 = "tests/adversarial/test_c2_emergent.py"


def case(case_id, layer, setup, invariant, expected, observed, status, evidence, severity, fix_owner):
    return {
        "case_id": case_id,
        "layer": layer,
        "setup": setup,
        "invariant": invariant,
        "expected": expected,
        "observed": observed,
        "status": status,
        "evidence": evidence,
        "severity": severity,
        "fix_owner": fix_owner,
    }


MATRIX: list[dict] = [
    # ---------------------------- B1 -----------------------------------------
    case("ADV-B1-01", B1, "governed canonical series with the correct provider symbol via a MONITORING:fred run",
         "MONITORING != FORMAL_OOS; correct identity is admissible for monitoring only",
         "series accepted, identity_verified true, formal authority absent",
         "accepted; source_refs ['fred:PAYEMS']; formal_admission_granted false", "PASS", f"{T_B1}::test_adv_b1_01_governed_identity_is_accepted_without_formal_authority", "none", "n/a"),
    case("ADV-B1-02", B1, "US_CORE_CPI rows persisted with source_series_id=PAYEMS",
         "provider/source identity mismatch != comparable series",
         "row is not usable evidence for US_CORE_CPI",
         "series BLOCKED, observations dropped, identity_blockers recorded", "FAIL_FIXED", f"{T_B1}::test_adv_b1_02_wrong_source_series_id_is_not_comparable_evidence", "P1", "WEEKEND-REDTEAM (fixed in this task)"),
    case("ADV-B1-03", B1, "MONITORING:fred run whose rows declare source='wind'",
         "NO_SILENT_SOURCE_FALLBACK; provider mismatch is never comparable",
         "row rejected rather than relabelled",
         "series BLOCKED; identity_blockers ['monitoring_source_mismatch:wind']", "FAIL_FIXED", f"{T_B1}::test_adv_b1_03_row_source_must_match_the_monitoring_run_provider", "P1", "WEEKEND-REDTEAM (fixed in this task)"),
    case("ADV-B1-04", B1, "binding config repeats a canonical series id",
         "duplicate canonical identity must not silently double-count",
         "ValueError at load time", "rejected: duplicate canonical series", "PASS", f"{T_B1}::test_adv_b1_04_duplicate_canonical_identity_in_binding_is_rejected", "none", "n/a"),
    case("ADV-B1-05", B1, "binding points at an enabled mapping with semantic_equivalence=false",
         "NO_PROXY_SUBSTITUTION", "ValueError at load time", "rejected: semantically equivalent source mapping", "PASS", f"{T_B1}::test_adv_b1_05_semantically_non_equivalent_proxy_cannot_be_bound", "none", "n/a"),
    case("ADV-B1-06", B1, "binding points at a disabled source mapping",
         "disabled mappings grant no authority", "ValueError at load time", "rejected", "PASS", f"{T_B1}::test_adv_b1_06_disabled_source_mapping_cannot_be_bound", "none", "n/a"),
    case("ADV-B1-07", B1, "binding references a series absent from config/series.yml",
         "NO_GUESSED_SOURCE_SEMANTICS", "ValueError at load time", "rejected: ungoverned canonical series", "PASS", f"{T_B1}::test_adv_b1_07_ungoverned_canonical_series_is_rejected", "none", "n/a"),
    case("ADV-B1-08", B1, "BOUND monitoring lane without a transform",
         "a bound factor must declare its causal transform", "ValueError at load time", "rejected: missing transform", "PASS", f"{T_B1}::test_adv_b1_08_bound_binding_requires_transform", "none", "n/a"),
    case("ADV-B1-09", B1, "monitoring identity that also carries a formal acceptance-registry row",
         "MONITORING != FORMAL_OOS; lane separation holds in both directions",
         "usage_separation MONITORING_NOT_FORMAL and no formal rows returned",
         "formal_readiness FORMAL_BLOCKED; formal query empty; pack grants no formal authority", "PASS", f"{T_B1}::test_adv_b1_09_formal_acceptance_does_not_leak_into_monitoring_pack", "none", "n/a"),
    case("ADV-B1-10", B1, "provider raises on fetch while an alternative enabled mapping exists",
         "NO_SILENT_SOURCE_FALLBACK", "run fails, zero rows, fallback=false recorded",
         "status failed, rows_written 0, attempts FAILED/fallback False", "PASS", f"{T_B1}::test_adv_b1_10_provider_error_never_triggers_silent_source_fallback", "none", "n/a"),
    case("ADV-B1-11", B1, "formal-provider (non MONITORING:) rows exist for a bound series",
         "monitoring read-model only consumes monitoring runs",
         "rows excluded from the pack", "observations empty; status MISSING/BLOCKED", "PASS", f"{T_B1}::test_adv_b1_11_formal_provider_rows_are_not_monitoring_evidence", "none", "n/a"),
    case("ADV-B1-12", B1, "Wind / iFinD / Tushare proprietary identities",
         "Wind-only lanes cannot be exercised without Wind",
         "explicit NOT_EXERCISED, providers stay disabled",
         "providers wind/ifind/tushare enabled=false in config/sources.yml", "NOT_EXERCISED", f"{T_B1}::test_adv_b1_12_wind_only_identity_is_not_exercisable_in_this_window", "none", "n/a (NO-WIND window)"),
    case("ADV-B1-13", B1, "binding references a factor_id absent from the taxonomy",
         "bindings cannot invent factors", "ValueError at load time", "rejected: unknown factor_id", "PASS", f"{T_B1}::test_adv_b1_13_binding_referencing_unknown_factor_is_rejected", "none", "n/a"),
    case("ADV-B1-14", B1, "lane status token outside {BOUND,UNBOUND,BLOCKED}",
         "lane status is a closed set", "ValueError at load time", "rejected: invalid monitoring status", "PASS", f"{T_B1}::test_adv_b1_14_invalid_lane_status_is_rejected", "none", "n/a"),
    case("ADV-B1-15", B1, "run provider has no enabled source mapping for the canonical series",
         "a provider symbol is not evidence without a governed mapping",
         "series represented as BLOCKED, not consumed",
         "identity_blockers ['monitoring_source_mapping_missing']", "PASS", f"{T_B1}::test_adv_b1_15_series_without_enabled_mapping_blocks_the_run", "none", "n/a"),
    case("ADV-B1-16", B1, "provider-contract unit vs catalog unit divergence for a monitoring series",
         "unit semantics are part of the identity contract",
         "mismatch should be detectable", "no unit cross-check exists in adapter or producer", "GAP_ADJACENT_WIP", "static-review: config/series.yml vs providers/monitoring.py FRED_MONITORING_CONTRACTS", "P2", "REAL-SNAPSHOT-V1 owner / WEB-CONTROL"),
    case("ADV-B1-17", B1, "manual (#93) source semantics used to manufacture test data",
         "NO_ADMISSION_RELAXATION; manual semantics must not be altered for tests",
         "no manual-source config changed", "no #93 / manual-source file modified by this task", "PASS", "git diff --stat on config/ and src/cross_asset/ingestion/manual_intake.py", "none", "n/a"),

    # ---------------------------- B2 -----------------------------------------
    case("ADV-B2-01", B2, "observation with available_at after the run decision_time",
         "no future information may enter the decision", "rejected", "ValueError: observation available after decision_time", "PASS", f"{T_B2}::test_adv_b2_01_observation_available_after_decision_time_is_rejected", "none", "n/a"),
    case("ADV-B2-02", B2, "observation_date after data_cutoff",
         "the cutoff is a hard evidence boundary", "rejected", "ValueError: observation after data_cutoff", "PASS", f"{T_B2}::test_adv_b2_02_observation_after_data_cutoff_is_rejected", "none", "n/a"),
    case("ADV-B2-03", B2, "duplicate observation dates with different available_at in the DB",
         "one vintage per observation date", "the latest available vintage wins, no double count",
         "48 distinct dates retained; revised value used", "PASS", f"{T_B2}::test_adv_b2_03_duplicate_dates_from_db_resolve_to_latest_vintage", "none", "n/a"),
    case("ADV-B2-04", B2, "hand-built pack with two rows for one observation date",
         "duplicate dates in the canonical pack contract should be explicit",
         "should be rejected or resolved", "accepted: the pack contract has no duplicate-date guard", "FAIL_BLOCKER", f"{T_B2}::test_adv_b2_04_duplicate_dates_in_direct_pack_are_not_guarded", "P2", "REAL-SNAPSHOT-V1 owner (diagnostic --input path only)"),
    case("ADV-B2-05", B2, "late-arriving row whose available_at is still <= decision_time",
         "late arrival is admissible only when causally visible",
         "row admitted, never after decision_time", "all observations <= decision_time", "PASS", f"{T_B2}::test_adv_b2_05_late_arriving_row_within_cutoff_is_admitted", "none", "n/a"),
    case("ADV-B2-06", B2, "a bound factor's canonical series is STALE",
         "stale evidence keeps reduced confidence, is not dropped or zero-filled",
         "confidence 0.5, stale flag set, score retained", "observed", "PASS", f"{T_B2}::test_adv_b2_06_stale_series_reduces_confidence_without_dropping_evidence", "none", "n/a"),
    case("ADV-B2-07", B2, "monitoring observation without available_at",
         "capture_time != first_release_time; availability is mandatory",
         "rejected", "pydantic ValidationError: available_at required", "PASS", f"{T_B2}::test_adv_b2_07_missing_available_at_is_rejected", "none", "n/a"),
    case("ADV-B2-08", B2, "full history captured at one timestamp (capture-time, non-PIT)",
         "capture-time history must never masquerade as PIT",
         "single availability vintage; no formal authority",
         "one distinct available_at; formal_admission_granted false", "PASS", f"{T_B2}::test_adv_b2_08_capture_time_history_never_grants_formal_or_pit_status", "none", "n/a"),
    case("ADV-B2-09", B2, "observations supplied out of chronological order",
         "the canonical contract is ordered", "rejected", "ValueError: not ordered", "PASS", f"{T_B2}::test_adv_b2_09_out_of_order_observations_are_rejected", "none", "n/a"),
    case("ADV-B2-10", B2, "fewer observations than the transform min_history",
         "insufficient transform history stays MISSING", "score None, missing True, reason recorded",
         "missing True; note 'transform unavailable: insufficient causal history'", "PASS", f"{T_B2}::test_adv_b2_10_insufficient_history_stays_missing_not_zero", "none", "n/a"),
    case("ADV-B2-11", B2, "the same observation persisted under two technical runs",
         "one observation is one observation", "counted once, deterministic ownership",
         "48 rows; one owning run id; idempotent insert", "PASS", f"{T_B2}::test_adv_b2_11_same_observation_under_two_runs_is_counted_once", "none", "n/a"),
    case("ADV-B2-12", B2, "available_at exactly equal to decision_time",
         "boundary is inclusive", "accepted", "snapshot produced", "PASS", f"{T_B2}::test_adv_b2_12_available_at_boundary_at_decision_time_is_inclusive", "none", "n/a"),
    case("ADV-B2-13", B2, "observation_date exactly equal to data_cutoff",
         "boundary is inclusive", "accepted", "snapshot produced with data_cutoff recorded", "PASS", f"{T_B2}::test_adv_b2_13_observation_date_boundary_at_cutoff_is_inclusive", "none", "n/a"),
    case("ADV-B2-14", B2, "pack.as_of earlier than lineage.data_cutoff",
         "display as_of and evidence cutoff must not silently disagree",
         "divergence should be rejected or normalised",
         "accepted: metadata.as_of and details.data_cutoff can disagree", "FAIL_BLOCKER", f"{T_B2}::test_adv_b2_14_as_of_cutoff_divergence_is_visible_in_the_snapshot", "P2", "REAL-SNAPSHOT-V1 owner"),
    case("ADV-B2-15", B2, "perfectly flat / zero-variance history for a regime axis",
         "UNKNOWN != ZERO; a flat prior is not a neutral z-score",
         "axis unavailable -> snapshot blocked, never 0.0", "MonitoringSnapshotBlocked", "PASS", f"{T_C2}::test_adv_e2_05_degenerate_flat_input_blocks_instead_of_reading_neutral", "none", "n/a"),

    # ---------------------------- B3 -----------------------------------------
    case("ADV-B3-01", B3, "US_EQ bound to the XNYS exchange calendar",
         "freshness is calendar-driven, not elapsed-hour", "OK with lag_sessions reported",
         "OK, calendar XNYS, lag 1", "PASS", f"{T_B3}::test_adv_b3_01_supported_exchange_calendar_is_fresh_within_lag", "none", "n/a"),
    case("ADV-B3-02", B3, "US Thanksgiving (2026-11-26) inside the lag window",
         "holiday boundary must not count as a missing session", "OK / lag 1; next session STALE / lag 2",
         "OK lag 1; 2026-11-27 STALE lag 2", "PASS", f"{T_B3}::test_adv_b3_02_holiday_is_not_counted_as_a_missing_session", "none", "n/a"),
    case("ADV-B3-03", B3, "series without a governed series->calendar mapping (5 canonical series)",
         "missing mapping fails closed", "BLOCKED with calendar_mapping_missing",
         "BLOCKED for CN_EQ_LARGE, COPPER, GOLD, US_CORE_CPI, US_NONFARM_PAYROLLS", "PASS", f"{T_B3}::test_adv_b3_03_unmapped_series_is_blocked_never_fresh", "none", "n/a"),
    case("ADV-B3-04", B3, "no observation at all for a mapped series",
         "missing evidence has its own reason", "BLOCKED no_formal_observation", "observed", "PASS", f"{T_B3}::test_adv_b3_04_no_observation_is_blocked_with_its_own_reason", "none", "n/a"),
    case("ADV-B3-05", B3, "market cutoff far outside exchange-calendar coverage",
         "calendar missing != fresh", "BLOCKED calendar_coverage_missing",
         "BLOCKED for both far-future and pre-coverage cutoffs", "PASS", f"{T_B3}::test_adv_b3_05_cutoff_outside_calendar_coverage_is_blocked", "none", "n/a"),
    case("ADV-B3-06", B3, "healthy / unmapped / no-observation series evaluated together",
         "stale vs missing vs blocked vs unknown stay distinct",
         "three distinct statuses", "OK / BLOCKED(mapping) / BLOCKED(no observation)", "PASS", f"{T_B3}::test_adv_b3_06_health_states_are_not_collapsed", "none", "n/a"),
    case("ADV-B3-07", B3, "an unmapped series whose observation equals the cutoff",
         "no Mon-Fri heuristic fallback", "BLOCKED, and no weekday logic in code",
         "BLOCKED; freshness.py contains no weekday/isoweekday logic", "PASS", f"{T_B3}::test_adv_b3_07_no_weekday_heuristic_in_the_freshness_path", "none", "n/a"),
    case("ADV-B3-08", B3, "invalid calendar entries (missing lag, negative lag, non-numeric lag, unnamed calendar, unknown source)",
         "invalid calendar configuration fails closed", "BLOCKED for every variant",
         "BLOCKED for all five variants", "PASS", f"{T_B3}::test_adv_b3_08_invalid_calendar_entries_fail_closed", "none", "n/a"),
    case("ADV-B3-09", B3, "publication series bound to an unverified project calendar",
         "calendar missing != fresh; unverified calendars grant nothing",
         "BLOCKED calendar_unverified", "observed", "PASS", f"{T_B3}::test_adv_b3_09_unverified_project_calendar_is_blocked", "none", "n/a"),
    case("ADV-B3-10", B3, "two series: one with calendar_mapping_missing, one with a schema error",
         "the narrow #129 downgrade must not absorb unrelated failures",
         "calendar-missing -> STALE+unverified; schema error -> BLOCKED",
         "US_CORE_CPI STALE freshness_verified=false; US_EQ BLOCKED", "PASS", f"{T_B3}::test_adv_b3_10_adapter_only_downgrades_the_governed_missing_calendar_reason", "none", "n/a"),
    case("ADV-B3-11", B3, "mapping loader with a missing file",
         "absent mapping config is empty, never assumed", "empty mapping; only US_EQ/HK_EQ governed",
         "observed", "PASS", f"{T_B3}::test_adv_b3_11_mapping_loader_is_explicit_and_fail_closed", "none", "n/a"),
    case("ADV-B3-12", B3, "CN interbank / make-up working-day calendar overlay",
         "special CN calendars need project-owned overlays", "not observable in this window",
         "no CN interbank calendar authority present; no Wind/CN local evidence", "NOT_EXERCISED", "static-review: config/calendars.yml marks CN capability_status UNVERIFIED", "none", "n/a (NO-WIND window)"),

    # ---------------------------- B4 -----------------------------------------
    case("ADV-B4-01", B4, "growth axis factor omitted from the pack",
         "MISSING != ZERO for the regime", "snapshot blocked, no synthesized axis",
         "MonitoringSnapshotBlocked 'regime axes unavailable'", "PASS", f"{T_B4}::test_adv_b4_01_missing_growth_axis_blocks_the_snapshot_instead_of_defaulting", "none", "n/a"),
    case("ADV-B4-02", B4, "inflation axis factor omitted",
         "MISSING != ZERO for the regime", "snapshot blocked", "observed", "PASS", f"{T_B4}::test_adv_b4_02_missing_inflation_axis_blocks_the_snapshot_instead_of_defaulting", "none", "n/a"),
    case("ADV-B4-03", B4, "one of three bound factors STALE",
         "one stale factor lowers its own confidence only",
         "0.5 for the stale factor, 1.0 for the rest", "observed", "PASS", f"{T_B4}::test_adv_b4_03_one_bound_factor_stale_keeps_reduced_confidence_only", "none", "n/a"),
    case("ADV-B4-04", B4, "taxonomy factor with no monitoring binding",
         "unbound factor must remain missing", "missing True, monitoring UNBOUND, score None",
         "observed for US_ISM_PMI", "PASS", f"{T_B4}::test_adv_b4_04_unbound_factor_remains_explicitly_missing", "none", "n/a"),
    case("ADV-B4-05", B4, "transform that contradicts the frozen factor definition",
         "wrong transform for a factor identity cannot be bound", "ValueError at load time",
         "rejected: violates V2 factor definition", "PASS", f"{T_B4}::test_adv_b4_05_wrong_transform_for_factor_identity_is_rejected", "none", "n/a"),
    case("ADV-B4-06", B4, "sign inversion attempt via the taxonomy sign field",
         "sign is applied exactly once at the scored boundary",
         "negative-sign lenses invert once; positive unchanged",
         "signed_score(-1 lens, 1.0) == -1.0; single application", "PASS", f"{T_B4}::test_adv_b4_06_sign_is_applied_exactly_once_at_the_taxonomy_boundary", "none", "n/a"),
    case("ADV-B4-07", B4, "same economic week retried three times",
         "same economic week retry != new regime week",
         "one economic week in history, dwell unchanged",
         "history ['2026-09-07']; dwell 1", "PASS", f"{T_B4}::test_adv_b4_07_same_economic_week_retry_never_creates_a_new_regime_week", "none", "n/a"),
    case("ADV-B4-08", B4, "three distinct economic weeks",
         "distinct weeks accumulate dwell", "three week ids, dwell 3",
         "history ['2026-09-07','2026-09-14','2026-09-21']; dwell 3", "PASS", f"{T_B4}::test_adv_b4_08_three_distinct_economic_weeks_accumulate_dwell", "none", "n/a"),
    case("ADV-B4-09", B4, "restart + replay versus continuous in-process build",
         "deterministic replay", "byte-identical snapshot",
         "to_json identical", "PASS", f"{T_B4}::test_adv_b4_09_restart_replay_matches_continuous_process", "none", "n/a"),
    case("ADV-B4-10", B4, "late-created backfill for an older economic week supplied as previous",
         "late technical creation != economic latest", "rejected",
         "ValueError previous_snapshot_must_precede_current_decision_time", "PASS", f"{T_B4}::test_adv_b4_10_backfilled_older_week_cannot_displace_the_economic_latest", "none", "n/a"),
    case("ADV-B4-11", B4, "future snapshot supplied as prior",
         "future snapshot != valid prior", "rejected", "observed", "PASS", f"{T_B4}::test_adv_b4_11_future_prior_is_rejected", "none", "n/a"),
    case("ADV-B4-12", B4, "axis scores exactly at the deadband edge and just outside it",
         "deadband hysteresis is exact and deterministic", "six documented outcomes",
         "0.25/-0.25 inside -> prior-inherited; 0.2500001 outside -> explicit quadrant", "PASS", f"{T_B4}::test_adv_b4_12_regime_deadband_and_exact_threshold_behaviour", "none", "n/a"),
    case("ADV-B4-13", B4, "axis score exactly 0.0 with an established prior",
         "inside the deadband the prior axis state is retained", "prior state retained",
         "growth_state and quadrant inherit the prior", "PASS", f"{T_B4}::test_adv_b4_13_axis_state_stickiness_inside_the_deadband", "none", "n/a"),
    case("ADV-B4-14", B4, "regime engine called with a None axis",
         "MISSING != ZERO at the engine boundary", "RegimeInsufficientDataError",
         "raised with 'MISSING != ZERO'", "PASS", f"{T_B4}::test_adv_b4_14_regime_engine_refuses_a_missing_axis", "none", "n/a"),
    case("ADV-B4-15", B4, "cluster with partial coverage",
         "partial coverage is reported, not smoothed away", "coverage 0.5 and missing list populated",
         "observed", "PASS", f"{T_B4}::test_adv_b4_15_partial_coverage_is_reported_not_smoothed_away", "none", "n/a"),
    case("ADV-B4-16", B4, "lens disagreement with fewer than two lenses",
         "disagreement needs at least two lenses", "no flag with one lens; flag above threshold",
         "observed", "PASS", f"{T_B4}::test_adv_b4_16_lens_disagreement_requires_two_lenses", "none", "n/a"),
    case("ADV-B4-17", B4, "aggregating CYCLICAL with TACTICAL, and STRUCTURAL_CONTEXT via aggregate_context",
         "horizons are never silently mixed", "HorizonMixingError", "raised", "PASS", f"{T_B4}::test_adv_b4_17_horizon_mixing_is_rejected", "none", "n/a"),
    case("ADV-B4-18", B4, "STRUCTURAL_CONTEXT score submitted to a macro aggregate",
         "structural context is display-only", "HorizonMixingError", "raised", "PASS", f"{T_B4}::test_adv_b4_18_structural_context_never_enters_a_macro_aggregate", "none", "n/a"),
    case("ADV-B4-19", B4, "SPREAD_CAUSAL_ZSCORE bound to a single series",
         "the spread transform requires exactly two series", "ValueError",
         "rejected: needs two series", "PASS", f"{T_B4}::test_adv_b4_19_spread_transform_requires_exactly_two_series", "none", "n/a"),
    case("ADV-B4-20", B4, "first snapshot with both axes inside the deadband",
         "an ambiguous first reading should not silently become a named quadrant",
         "explicit unknown would be preferable to a default label",
         "resolves to the documented default GOLDILOCKS (deadband inherits the default prior)", "FAIL_BLOCKER", f"{T_B4}::test_adv_b4_20_first_snapshot_all_deadband_resolves_via_the_documented_default", "P2", "Decision-Support-V2 owner / WEB-CONTROL"),
    case("ADV-B4-21", B4, "CHANGE_CAUSAL_ZSCORE with min_history above the available rows",
         "min_history is enforced per transform", "missing True",
         "observed", "PASS", f"{T_B4}::test_adv_b4_21_change_transform_respects_min_history", "none", "n/a"),

    # ---------------------------- B5 -----------------------------------------
    case("ADV-B5-01", B5, "all macro clusters for US_EQ unavailable",
         "no macro basis -> explicit neutral, never a guess", "bias 0, stance 0, health MISSING",
         "observed; valuation_tag 'macro basis unavailable; explicit neutral stance'", "PASS", f"{T_B5}::test_adv_b5_01_missing_macro_basis_yields_explicit_neutral_stance", "none", "n/a"),
    case("ADV-B5-02", B5, "one of several macro clusters unavailable",
         "missing clusters are excluded, never zero-filled", "available/missing counted; confidence scaled",
         "confidence_factor == available/declared", "PASS", f"{T_B5}::test_adv_b5_02_partial_macro_basis_excludes_missing_and_lowers_confidence", "none", "n/a"),
    case("ADV-B5-03", B5, "confirmation score matrix (None, 0.0, aligned, opposed, zero bias)",
         "UNKNOWN != DIVERGENT != COUNTER_TREND != CONFIRMED", "six documented outcomes",
         "observed", "PASS", f"{T_B5}::test_adv_b5_03_confirmation_state_matrix", "none", "n/a"),
    case("ADV-B5-04", B5, "confirmation input unobservable",
         "an unobserved input is UNKNOWN, never a fabricated divergence",
         "UNKNOWN, blocker recorded, confidence discounted, stance unadjusted",
         "observed", "PASS", f"{T_B5}::test_adv_b5_04_unobservable_confirmation_is_unknown_not_divergent", "none", "n/a"),
    case("ADV-B5-05", B5, "market confirmation opposes the macro bias for every stance",
         "confirmation may cap but never flips the macro sign", "|stance| <= cap and sign preserved",
         "observed for stances -2..2", "PASS", f"{T_B5}::test_adv_b5_05_confirmation_conflict_caps_but_never_flips_the_sign", "none", "n/a"),
    case("ADV-B5-06", B5, "observed flat confirmation (DIVERGENT)",
         "divergence attenuates one step toward neutral", "one step toward zero",
         "observed", "PASS", f"{T_B5}::test_adv_b5_06_divergent_attenuates_one_step_toward_neutral", "none", "n/a"),
    case("ADV-B5-07", B5, "valuation exactly at cap/cushion thresholds and unbound",
         "valuation cap/cushion edges are exact and asymmetric", "seven documented outcomes",
         "cap applies at <= -1.0; cushion at >= 1.0; unbound leaves stance untouched", "PASS", f"{T_B5}::test_adv_b5_07_valuation_cap_and_cushion_edges", "none", "n/a"),
    case("ADV-B5-08", B5, "very cheap valuation against a short stance",
         "a cheap valuation cushions but never creates a long", "stance stays short",
         "-2 -> -1", "PASS", f"{T_B5}::test_adv_b5_08_cheap_valuation_never_upgrades_a_short_stance", "none", "n/a"),
    case("ADV-B5-09", B5, "contributions that oppose the resulting stance",
         "counter-signals surface genuine disagreement", "counter_signals populated",
         "observed", "PASS", f"{T_B5}::test_adv_b5_09_counter_signals_are_emitted_for_opposing_contributions", "none", "n/a"),
    case("ADV-B5-10", B5, "confirmation factor missing for US_EQ",
         "missing factor must not become bearish", "stance >= 0, health degraded, UNKNOWN",
         "observed", "PASS", f"{T_B5}::test_adv_b5_10_missing_confirmation_factor_does_not_turn_an_asset_bearish", "none", "n/a"),
    case("ADV-B5-11", B5, "only the market-confirmation factor available",
         "market confirmation must not silently become macro authority",
         "macro_bias 0 and stance 0", "observed", "PASS", f"{T_B5}::test_adv_b5_11_confirmation_only_factor_never_sets_macro_bias", "none", "n/a"),
    case("ADV-B5-12", B5, "confirmation aligned with the macro bias",
         "confirmation is attributed as market, not as macro", "market_confirmed driver tag present",
         "observed", "PASS", f"{T_B5}::test_adv_b5_12_confirmed_state_is_attributed_to_the_confirmation_source", "none", "n/a"),
    case("ADV-B5-13", B5, "every configured asset rule evaluated",
         "stances stay within [-2,2] and every rule publishes an invalidator",
         "all asset views bounded", "observed for all 8 configured assets", "PASS", f"{T_B5}::test_adv_b5_13_all_asset_stances_stay_inside_bounds", "none", "n/a"),
    case("ADV-B5-14", B5, "UNKNOWN versus CONFIRMED confirmation confidence",
         "the UNKNOWN discount is an explicit named constant", "discount == 0.7",
         "observed", "PASS", f"{T_B5}::test_adv_b5_14_unknown_confirmation_discount_is_the_named_constant", "none", "n/a"),

    # ---------------------------- B6 -----------------------------------------
    case("ADV-B6-01", B6, "two independently built snapshots from identical inputs",
         "snapshot serialization deterministic", "byte-identical JSON and identical snapshot_id",
         "observed", "PASS", f"{T_B6}::test_adv_b6_01_snapshot_serialization_is_deterministic_and_round_trips", "none", "n/a"),
    case("ADV-B6-02", B6, "no latest.json present",
         "missing pointer is DEGRADED, never fabricated", "health DEGRADED; latest raises",
         "observed", "PASS", f"{T_B6}::test_adv_b6_02_missing_latest_pointer_is_degraded_not_fabricated", "none", "n/a"),
    case("ADV-B6-03", B6, "empty snapshot root",
         "empty root serves only contract metadata", "factors OK; snapshot routes raise",
         "observed", "PASS", f"{T_B6}::test_adv_b6_03_empty_snapshot_root_serves_factors_but_no_snapshot", "none", "n/a"),
    case("ADV-B6-04", B6, "corrupted latest.json",
         "malformed state is reported as a typed store error, not raw internals",
         "typed SnapshotStoreError",
         "raw pydantic ValidationError surfaces (HTTP maps it to an opaque 404)", "FAIL_BLOCKER", f"{T_B6}::test_adv_b6_04_corrupted_latest_pointer_is_reported_not_ignored", "P2", "PR #135 (serving.py owner)"),
    case("ADV-B6-05", B6, "malformed snapshot file served over HTTP",
         "no fabricated health payload", "non-200, fail closed", "404", "PASS", f"{T_B6}::test_adv_b6_05_malformed_snapshot_file_is_not_served", "none", "n/a"),
    case("ADV-B6-06", B6, "older backfilled snapshot persisted after a newer one",
         "late technical creation != economic latest",
         "latest pointer must remain on the economically newest snapshot",
         "latest.json is overwritten by the backfill", "FAIL_BLOCKER", f"{T_B6}::test_adv_b6_06_backfilled_older_snapshot_must_not_become_latest", "P1", "PR #135 (serving.py owner)"),
    case("ADV-B6-07", B6, "same pack built with and without previous_snapshot",
         "snapshot identity must cover everything that changes the body",
         "distinct ids for distinct bodies",
         "identical snapshot_id for different bodies (store would silently overwrite)", "FAIL_BLOCKER", f"{T_B6}::test_adv_b6_07_snapshot_id_ignores_previous_snapshot_lineage", "P2", "REAL-SNAPSHOT-V1 owner / PR #133-#135"),
    case("ADV-B6-08", B6, "path-traversal snapshot ids",
         "no filesystem escape from the snapshot root", "rejected", "ValueError/FileNotFoundError for all variants", "PASS", f"{T_B6}::test_adv_b6_08_path_traversal_ids_are_rejected", "none", "n/a"),
    case("ADV-B6-09", B6, "unknown routes, unknown ids, empty id, unknown asset",
         "API 404 semantics", "404 for each", "observed", "PASS", f"{T_B6}::test_adv_b6_09_unknown_routes_and_ids_return_404", "none", "n/a"),
    case("ADV-B6-10", B6, "write verbs against the read-only API",
         "no mutation routes", "non-2xx for POST/PUT/DELETE/PATCH",
         "404/501", "PASS", f"{T_B6}::test_adv_b6_10_api_exposes_only_read_routes", "none", "n/a"),
    case("ADV-B6-11", B6, "HTTP response headers on a successful read",
         "snapshots are not cached", "Cache-Control: no-store", "observed", "PASS", f"{T_B6}::test_adv_b6_11_successful_reads_are_uncacheable", "none", "n/a"),
    case("ADV-B6-12", B6, "API payload validated against DashboardSnapshotV0",
         "API payload contract", "payload reparses to an equal model",
         "semantically equal (model_dump equal)", "PASS", f"{T_B6}::test_adv_b6_12_api_payload_satisfies_the_snapshot_contract", "none", "n/a"),
    case("ADV-B6-13", B6, "HTTP-layer JSON key ordering versus model serialization",
         "to_json documents sorted keys", "byte-identical ordering",
         "HTTP layer sorts keys; the model preserves details insertion order (semantically equal)", "FAIL_BLOCKER", f"{T_B6}::test_adv_b6_12b_http_layer_sorts_keys_while_the_model_does_not", "P2", "PR #135 (serving.py owner) / REAL-SNAPSHOT-V1 owner"),
    case("ADV-B6-14", B6, "persist leaves no temporary files",
         "atomic writes", "no *.tmp remainder", "observed", "PASS", f"{T_B6}::test_adv_b6_13_persist_leaves_no_temporary_or_partial_files", "none", "n/a"),
    case("ADV-B6-15", B6, "three same-week technical snapshots persisted",
         "same-week retries coexist without silently overwriting each other",
         "three distinct files and ids", "observed", "PASS", f"{T_B6}::test_adv_b6_14_same_week_technical_snapshots_coexist_without_overwrite", "none", "n/a"),
    case("ADV-B6-16", B6, "history enumeration and current/prior diff surfaces",
         "decision history is a required product surface",
         "present on merged main", "absent on baseline main; owned by PR #135", "GAP_ADJACENT_WIP", f"{T_B6}::test_adv_b6_15_history_and_diff_surfaces_are_absent_on_current_main", "none", "PR #135 / issue #133"),
    case("ADV-B6-17", B6, "snapshot whose id is literally 'latest'",
         "route identity is unambiguous", "benign alias at worst",
         "load('latest') resolves the same pointer as the latest route", "PASS", f"{T_B6}::test_adv_b6_16_latest_endpoint_is_not_shadowed_by_id_routing", "none", "n/a"),

    # ---------------------------- B7 -----------------------------------------
    case("ADV-B7-01", B7, "information-set status classification",
         "UPDATED / OVERDUE_STALE / NO_NEW_INFORMATION are distinct", "three statuses",
         "observed", "PASS", f"{T_B7}::test_adv_b7_01_information_set_status_classification", "none", "n/a"),
    case("ADV-B7-02", B7, "macro factor moves without an observed release",
         "NO_OUTCOME_DRIVEN_TUNING; synthetic movement forbidden", "SyntheticMovementError",
         "raised for both NO_NEW_INFORMATION and UPDATED-without-release", "PASS", f"{T_B7}::test_adv_b7_02_macro_movement_without_new_information_is_forbidden", "none", "n/a"),
    case("ADV-B7-03", B7, "same-week retry of the weekly-change surfaces",
         "a retry is not a new week", "information-set and asset deltas carried over",
         "observed", "PASS", f"{T_B7}::test_adv_b7_03_same_week_retry_preserves_weekly_change_surfaces", "none", "n/a"),
    case("ADV-B7-04", B7, "real DB adapter pack inspected for release/market evidence",
         "information-set delta must reflect real releases and market moves",
         "release_events / expected_releases / market_moves populated from the DB",
         "all four surfaces empty: every real snapshot reports NO_NEW_INFORMATION with 0 market moves", "FAIL_BLOCKER", f"{T_B7}::test_adv_b7_04_real_db_adapter_supplies_no_release_or_market_evidence", "P1", "REAL-SNAPSHOT-V1 owner / WEB-CONTROL"),
    case("ADV-B7-05", B7, "market move unit semantics per metric class",
         "unit semantics are enforced per class", "BPS/PCT/POINT as configured",
         "YIELD/SPREAD -> BPS; PRICE/FX -> PCT; VOLATILITY -> configured style", "PASS", f"{T_B7}::test_adv_b7_05_market_move_units", "none", "n/a"),
    case("ADV-B7-06", B7, "ratio-class market move with a zero prior value",
         "no infinite/undefined weekly change", "ValueError",
         "rejected", "PASS", f"{T_B7}::test_adv_b7_06_zero_prior_ratio_move_is_rejected", "none", "n/a"),
    case("ADV-B7-07", B7, "late-created backfill run versus true economic prior",
         "late technical creation != economic latest (formal lineage)",
         "the economically latest eligible run wins", "wb-adv-newer selected", "PASS", f"{T_B7}::test_adv_b7_07_late_created_backfill_does_not_displace_economic_prior", "none", "n/a"),
    case("ADV-B7-08", B7, "FIXTURE/SIMULATED runs claiming a formal previous-valid",
         "MONITORING/FIXTURE can never enter formal lineage",
         "only LIVE is eligible", "LIVE true; FIXTURE/SIMULATED false", "PASS", f"{T_B7}::test_adv_b7_08_monitoring_run_cannot_claim_formal_previous_valid", "none", "n/a"),
    case("ADV-B7-09", B7, "FIXTURE run declaring previous_valid_source='formal'",
         "fixture cannot inherit formal lineage", "ValueError at validate()",
         "rejected", "PASS", f"{T_B7}::test_adv_b7_09_fixture_run_cannot_claim_a_formal_previous_valid_source", "none", "n/a"),
    case("ADV-B7-10", B7, "product monitoring bindings on merged main",
         "no admission relaxation and no scope inflation",
         "exactly the seven accepted bindings, formal BLOCKED",
         "seven bound; all formal statuses BLOCKED", "PASS", f"{T_B7}::test_adv_b7_10_product_monitoring_bindings_are_exactly_the_accepted_seven", "none", "n/a"),
    case("ADV-B7-11", B7, "frontend normal path on API failure",
         "API failure != fixture fallback; FRONTEND_BUSINESS_LOGIC = FORBIDDEN",
         "API-first default, visible failure, no fixture substitution",
         "loader defaults to 'api' outside test mode; App.jsx sets bundle null and surfaces the error", "PASS", f"{T_B7}::test_adv_b7_11_frontend_normal_path_cannot_fall_back_to_demo_fixtures", "none", "n/a"),
    case("ADV-B7-12", B7, "weekly semantic comparability gate",
         "lookback/source changes must be comparable",
         "gate present on merged main", "absent on baseline main; owned by PR #132 / issue #131", "GAP_ADJACENT_WIP", f"{T_B7}::test_adv_b7_12_weekly_comparability_gate_is_owned_by_131_132", "none", "PR #132 / issue #131"),

    # ---------------------------- B8 -----------------------------------------
    case("ADV-B8-01", B8, "default host for the snapshot API",
         "the read-only API is not publicly exposed by default", "127.0.0.1",
         "observed; no 0.0.0.0 in the serving CLI", "PASS", f"{T_B8}::test_adv_b8_01_api_defaults_to_loopback_and_is_not_publicly_exposed", "none", "n/a"),
    case("ADV-B8-02", B8, "default host for the operational snapshot CLI",
         "CLI serve also loopback-only", "127.0.0.1", "observed", "PASS", f"{T_B8}::test_adv_b8_02_snapshot_cli_serve_also_defaults_to_loopback", "none", "n/a"),
    case("ADV-B8-03", B8, "runtime dependency surface",
         "no new web framework introduced", "stdlib http.server only",
         "no fastapi/flask/uvicorn/starlette/django in pyproject", "PASS", f"{T_B8}::test_adv_b8_03_no_web_framework_is_introduced", "none", "n/a"),
    case("ADV-B8-04", B8, "server shutdown while serving",
         "clean shutdown, no orphan thread", "thread exits",
         "observed", "PASS", f"{T_B8}::test_adv_b8_04_server_shuts_down_cleanly", "none", "n/a"),
    case("ADV-B8-05", B8, "eight concurrent readers against one snapshot",
         "threaded read server is consistent", "identical payloads, no errors",
         "8/8 identical snapshot ids", "PASS", f"{T_B8}::test_adv_b8_05_concurrent_reads_are_consistent", "none", "n/a"),
    case("ADV-B8-06", B8, "Python runtime process-spawning surface",
         "no child-process ownership from the Python API layer", "no subprocess/os.system",
         "observed in serving/snapshot_cli/producer", "PASS", f"{T_B8}::test_adv_b8_06_python_runtime_spawns_no_child_processes", "none", "n/a"),
    case("ADV-B8-07", B8, "native Windows launcher process ownership",
         "native process semantics need native proof",
         "external evidence from #136",
         "launcher/ and START_MACRO_WORKBENCH.cmd are not on baseline main", "NOT_EXERCISED", f"{T_B8}::test_adv_b8_07_native_windows_process_semantics_are_not_exercised_here", "none", "PR #136 / issue #134"),
    case("ADV-B8-08", B8, "read endpoints versus store mutation",
         "the API is read-only", "byte-identical store before and after",
         "observed", "PASS", f"{T_B8}::test_adv_b8_08_read_api_never_mutates_the_store", "none", "n/a"),

    # ------------------- Pass 2 — emergent cross-layer ------------------------
    case("ADV-E2-01", P2, "week 2 of the real DB path where a new monthly observation moves a cyclical factor",
         "MONITORING != FORMAL_OOS; information-set status must be causally true",
         "the second week produces a snapshot (or a typed DATA_BLOCKED), not an exception",
         "SyntheticMovementError raised: the normal multi-week monitoring loop cannot produce week 2", "FAIL_BLOCKER", f"{T_C2}::test_adv_e2_01_real_second_week_with_new_data_raises_synthetic_movement", "P1", "REAL-SNAPSHOT-V1 owner / WEB-CONTROL (needs a release-event policy decision)"),
    case("ADV-E2-02", C2 := P2, "week 2 with no new cyclical observation",
         "the failure above must be data-driven, not a lineage bug",
         "the same call succeeds", "snapshot produced", "PASS", f"{T_C2}::test_adv_e2_02_real_second_week_without_new_data_is_still_producible", "none", "n/a"),
    case("ADV-E2-03", P2, "within-week retry where the market confirmation flips",
         "weekly-change surfaces must describe real within-week movement",
         "the copied delta should reflect the changed asset surface",
         "asset views change while the copied asset_view_delta stays empty", "FAIL_BLOCKER", f"{T_C2}::test_adv_e2_03_same_week_retry_can_desynchronise_delta_and_views", "P2", "REAL-SNAPSHOT-V1 owner / PR #133-#135"),
    case("ADV-E2-04", P2, "restart with legacy regime rows that have no economic week id",
         "history canonicalization must not inflate dwell weeks",
         "only the last legacy row is migrated",
         "exactly two weeks: one migrated legacy week plus the current week", "PASS", f"{T_C2}::test_adv_e2_04_legacy_unkeyed_regime_rows_are_not_replayed_as_many_weeks", "none", "n/a"),
    case("ADV-E2-05", P2, "degenerate flat monitoring history",
         "a zero-variance prior is not a neutral signal",
         "axis unavailable -> blocked", "MonitoringSnapshotBlocked", "PASS", f"{T_C2}::test_adv_e2_05_degenerate_flat_input_blocks_instead_of_reading_neutral", "none", "n/a"),
    case("ADV-E2-06", P2, "freshness downgrade applied by the adapter (#129 narrow exception)",
         "a calendar downgrade must not fabricate coverage or confidence",
         "STALE with reduced confidence and explicit freshness_limitation",
         "confidence 0.5, freshness_verified false, limitation calendar_mapping_missing", "PASS", f"{T_C2}::test_adv_e2_06_missing_calendar_downgrade_does_not_fabricate_coverage", "none", "n/a"),
    case("ADV-E2-07", P2, "series whose persisted rows fail the identity check",
         "a blocked series must remain visible as BLOCKED, not vanish",
         "series enumerated with BLOCKED and blockers",
         "US_CORE_CPI BLOCKED with identity_blockers; factor reported missing", "PASS", f"{T_C2}::test_adv_e2_07_identity_blocked_series_remains_visible_as_blocked", "none", "n/a"),
    case("ADV-E2-08", P2, "identity-validated pack carried through to the snapshot binding record",
         "fixing identity validation must not create formal authority",
         "formal stays BLOCKED end to end",
         "record formal.status BLOCKED; lane MONITORING", "PASS", f"{T_C2}::test_adv_e2_08_identity_fix_does_not_grant_formal_authority", "none", "n/a"),
    case("ADV-E2-09", P2, "latest pointer holding a later decision_time than the current run",
         "CLI previous selection must never look ahead",
         "no previous snapshot selected",
         "None for the earlier run; selected for the later run", "PASS", f"{T_C2}::test_adv_e2_09_cli_previous_selection_rejects_a_look_ahead_latest_pointer", "none", "n/a"),
    case("ADV-E2-10", P2, "governed DB -> pack -> snapshot -> store -> HTTP after the identity fix",
         "the full chain stays truthful after a narrow fix",
         "identity_verified true end to end and health PARTIAL",
         "observed", "PASS", f"{T_C2}::test_adv_e2_10_full_chain_from_governed_db_to_http_after_identity_fix", "none", "n/a"),
    case("ADV-E2-11", P2, "release-event derivation policy for the monitoring lane",
         "deciding what counts as new information is a product-policy choice",
         "not decided by this window",
         "requires first-release/vintage semantics that the MONITORING lane does not claim", "BLOCKED_POLICY", "Phase D analysis, see REDTEAM_PASSES.md pass 2", "P1", "WEB-CONTROL / REAL-SNAPSHOT-V1 owner"),
]

# --------------------------------------------------------------------------- #
# Blocker ledger
# --------------------------------------------------------------------------- #

LEDGER = [
    {
        "id": "ADV-P1-01",
        "severity": "P1",
        "invariant": "capture_time != first_release_time; MONITORING != FORMAL_OOS",
        "title": "Real multi-week monitoring loop cannot produce week 2 once new monthly data arrives",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_c2_emergent.py -k e2_01",
            "or: build_monitoring_pack_from_db(store, workbench_run(week1)) -> build_monitoring_snapshot -> ok",
            "then: build_monitoring_pack_from_db(store, workbench_run(week2 with a new monthly row)) ->",
            "build_monitoring_snapshot(pack2, previous_snapshot=snapshot1) raises SyntheticMovementError",
        ],
        "affected_path": "src/cross_asset/decision_support/monitoring_adapter.py -> producer.build_monitoring_snapshot -> weekly.build_macro_state_delta",
        "current_evidence": "tests/adversarial/test_c2_emergent.py::test_adv_e2_01...; tests/adversarial/test_b7_weekly_lane.py::test_adv_b7_04...",
        "root_cause_hypothesis": "build_monitoring_pack_from_db never populates release_events/expected_releases, so information_set_delta.status is always NO_NEW_INFORMATION while cyclical factor scores genuinely move; the producer's synthetic-movement guard then (correctly) refuses to emit the week.",
        "fixability": "NOT FIXED BY THIS WINDOW — requires a product-policy decision about what constitutes a new release for the monitoring lane (first-release vs capture-time, revision handling). Any narrow implementation would invent that policy.",
        "owner": "REAL-SNAPSHOT-V1 owner (ONLINE-DEV-A) with WEB-CONTROL coordination",
        "status": "OPEN / BLOCKER",
        "overlap_check": "monitoring_adapter.py and producer.py are not touched by PR #135/#132/#136; the policy decision is adjacent to #133/#135 multi-week continuity, so it must not be fixed unilaterally.",
    },
    {
        "id": "ADV-P1-02",
        "severity": "P1",
        "invariant": "late technical creation != economic latest",
        "title": "SnapshotStore.persist has no economic monotonicity guard on the latest pointer",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b6_snapshot_api.py -k b6_06",
            "persist a snapshot with as_of 2026-09-18, then persist a backfilled snapshot with as_of 2026-09-11",
            "SnapshotStore.load_latest() now returns the older snapshot",
        ],
        "affected_path": "src/cross_asset/decision_support/serving.py (SnapshotStore.persist/load_latest)",
        "current_evidence": "tests/adversarial/test_b6_snapshot_api.py::test_adv_b6_06_backfilled_older_snapshot_must_not_become_latest",
        "root_cause_hypothesis": "latest.json is written unconditionally on every persist; the pointer is ordered by write time, not by (as_of, decision_time).",
        "fixability": "NOT FIXED BY THIS WINDOW — serving.py is inside PR #135's active edit surface.",
        "owner": "PR #135 / issue #133 (DECISION-HISTORY-V1)",
        "status": "OPEN / BLOCKER",
        "overlap_check": "serving.py is modified by PR #135; a competing edit would create a real conflict. The CLI mitigates by never looking ahead (ADV-E2-09) but direct store use does not.",
    },
    {
        "id": "ADV-P2-01",
        "severity": "P2",
        "invariant": "provider/source identity mismatch != comparable series",
        "title": "Monitoring read model did not re-validate persisted row identity (FIXED)",
        "exact_reproduction": [
            "before the fix: persist US_CORE_CPI rows with source_series_id=PAYEMS under a MONITORING:fred run",
            "build_monitoring_pack_from_db -> US_CORE_CPI accepted with source_refs ['fred:PAYEMS']",
        ],
        "affected_path": "src/cross_asset/decision_support/monitoring_adapter.py",
        "current_evidence": "tests/adversarial/test_b1_identity_source.py::test_adv_b1_02, ::test_adv_b1_03, ::test_adv_b1_15",
        "root_cause_hypothesis": "MonitoringRunner._validate_rows enforces identity at ingestion, but the read model is a separate boundary where rows may have been written directly or by another window.",
        "fixability": "FIXED — narrow fail-closed validation reusing the accepted catalog.expected_source_identities authority; violating series are represented as BLOCKED with explicit identity_blockers, mirroring MONITORING_SCHEMA_ERROR -> FAILED -> BLOCKED.",
        "owner": "WEEKEND-REDTEAM (this task)",
        "status": "FIXED / REGRESSION-TESTED",
        "overlap_check": "monitoring_adapter.py is not in any of PR #135/#132/#136; no product/economic policy changed.",
    },
    {
        "id": "ADV-P2-02",
        "severity": "P2",
        "invariant": "duplicate observation dates are not comparable evidence",
        "title": "Direct MonitoringObservationPack contract has no duplicate-observation-date guard",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b2_time_causality.py -k b2_04",
            "append two rows with the same observation_date and different available_at to a hand-built pack",
            "build_monitoring_snapshot accepts it",
        ],
        "affected_path": "src/cross_asset/decision_support/producer.py (_validate_pack)",
        "current_evidence": "tests/adversarial/test_b2_time_causality.py::test_adv_b2_04_duplicate_dates_in_direct_pack_are_not_guarded",
        "root_cause_hypothesis": "The ordering check does not imply de-duplication; the DB read model resolves duplicates by latest vintage (ADV-B2-03), so only hand-built packs are affected.",
        "fixability": "NOT FIXED — the correct resolution (reject vs latest-vintage-wins) is a contract decision, and the affected surface is the diagnostic --input path.",
        "owner": "REAL-SNAPSHOT-V1 owner",
        "status": "OPEN / LOW-IMPACT",
        "overlap_check": "producer.py not in PR #135/#132/#136.",
    },
    {
        "id": "ADV-P2-03",
        "severity": "P2",
        "invariant": "one snapshot identity must correspond to one economic state",
        "title": "metadata.as_of may diverge from details.data_cutoff in the pack contract",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b2_time_causality.py -k b2_14",
            "build a pack whose as_of is 30 days before lineage.data_cutoff",
            "the snapshot is accepted; metadata.as_of is the older date while details.data_cutoff is the newer one",
        ],
        "affected_path": "src/cross_asset/decision_support/producer.py + monitoring_adapter.py",
        "current_evidence": "tests/adversarial/test_b2_time_causality.py::test_adv_b2_14_as_of_cutoff_divergence_is_visible_in_the_snapshot",
        "root_cause_hypothesis": "as_of is treated as a display field while data_cutoff carries the evidence boundary; the runtime adapter always sets them equal, so only hand-built packs diverge.",
        "fixability": "NOT FIXED — needs a decision on whether as_of is derived from data_cutoff or independently meaningful.",
        "owner": "REAL-SNAPSHOT-V1 owner",
        "status": "OPEN / LOW-IMPACT",
        "overlap_check": "producer.py not in PR #135/#132/#136.",
    },
    {
        "id": "ADV-P2-04",
        "severity": "P2",
        "invariant": "NO_GUESSED_SOURCE_SEMANTICS / MISSING != ZERO",
        "title": "First snapshot with both regime axes inside the deadband resolves to a named quadrant",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b4_factor_regime.py -k b4_20",
            "RegimeEngine(axis_threshold=0.25).candidate_quadrant(0.0, 0.0, prior=None) -> GOLDILOCKS",
        ],
        "affected_path": "src/cross_asset/decision_support/regime.py (candidate_quadrant default prior)",
        "current_evidence": "tests/adversarial/test_b4_factor_regime.py::test_adv_b4_20_first_snapshot_all_deadband_resolves_via_the_documented_default; tests/unit/decision_support/test_regime.py::test_initial_state_without_prior",
        "root_cause_hypothesis": "Deadband hysteresis inherits a prior quadrant; with no prior it defaults to GOLDILOCKS, so an ambiguous first reading becomes a specific economic label.",
        "fixability": "NOT FIXED — changing the first-snapshot label changes product semantics and would invalidate accepted Scope E behaviour.",
        "owner": "Decision-Support-V2 owner / WEB-CONTROL",
        "status": "OPEN / DIAGNOSABILITY",
        "overlap_check": "regime.py not in PR #135/#132/#136.",
    },
    {
        "id": "ADV-P2-05",
        "severity": "P2",
        "invariant": "failure semantics must be typed and must not leak internals",
        "title": "A corrupted latest.json surfaces a raw pydantic ValidationError",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b6_snapshot_api.py -k b6_04",
            "write '{ not json' to <root>/latest.json, then call SnapshotReadService.health()",
            "a pydantic ValidationError propagates (the HTTP layer turns it into a 404 carrying that text)",
        ],
        "affected_path": "src/cross_asset/decision_support/serving.py",
        "current_evidence": "tests/adversarial/test_b6_snapshot_api.py::test_adv_b6_04..., ::test_adv_b6_05..., ::test_adv_b6_12b...",
        "root_cause_hypothesis": "health() only guards FileNotFoundError; parse/validation failures fall through the generic ValueError handler and lose their severity semantics.",
        "fixability": "NOT FIXED — serving.py is inside PR #135's active edit surface.",
        "owner": "PR #135 / issue #133",
        "status": "OPEN / BLOCKER (overlap)",
        "overlap_check": "serving.py is modified by PR #135.",
    },
    {
        "id": "ADV-P2-06",
        "severity": "P2",
        "invariant": "one snapshot id == one snapshot body",
        "title": "snapshot_id does not cover previous_snapshot, so distinct bodies can collide",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b6_snapshot_api.py -k b6_07",
            "build the same pack with and without previous_snapshot",
            "identical snapshot_id, different serialized bodies",
        ],
        "affected_path": "src/cross_asset/decision_support/producer.py (_snapshot_id)",
        "current_evidence": "tests/adversarial/test_b6_snapshot_api.py::test_adv_b6_07_snapshot_id_ignores_previous_snapshot_lineage",
        "root_cause_hypothesis": "The hash covers the pack, registry version, taxonomy version and model version, but not the lineage inputs that change regime dwell and weekly deltas.",
        "fixability": "NOT FIXED — changing the identity formula alters persisted snapshot ids and interacts with #133/#135 history.",
        "owner": "REAL-SNAPSHOT-V1 owner with PR #133/#135",
        "status": "OPEN / LOW-IMPACT (store would silently overwrite)",
        "overlap_check": "producer.py not in PR #135/#132/#136, but the identity contract is shared with decision history.",
    },
    {
        "id": "ADV-P2-07",
        "severity": "P2",
        "invariant": "documented serialization contract must match behaviour",
        "title": "to_json documents 'sorted keys' but preserves details insertion order; the HTTP layer sorts",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b6_snapshot_api.py -k b6_12b",
            "compare snapshot.to_json() bytes with the /api/snapshot/latest payload bytes for the same snapshot",
        ],
        "affected_path": "src/cross_asset/decision_support/snapshot.py (to_json) and serving.py (_Handler._json)",
        "current_evidence": "tests/adversarial/test_b6_snapshot_api.py::test_adv_b6_12b_http_layer_sorts_keys_while_the_model_does_not",
        "root_cause_hypothesis": "pydantic model_dump_json preserves mapping order; the docstring overstates the guarantee.",
        "fixability": "NOT FIXED — either the docstring or the serializer must change, and serving.py overlaps PR #135.",
        "owner": "PR #135 (serving.py) / REAL-SNAPSHOT-V1 owner (docstring)",
        "status": "OPEN / DIAGNOSABILITY",
        "overlap_check": "both files touch PR #135's surface or its neighbours.",
    },
    {
        "id": "ADV-P2-08",
        "severity": "P2",
        "invariant": "weekly-change surfaces must describe real week-over-week movement",
        "title": "Same-week retry copies the prior asset delta while recomputing the asset views",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_c2_emergent.py -k e2_03",
            "build week W, then a same-week retry whose market confirmation flips",
            "the retry's asset views change while its copied asset_view_delta stays empty",
        ],
        "affected_path": "src/cross_asset/decision_support/producer.py (build_monitoring_snapshot same_week_retry branch)",
        "current_evidence": "tests/adversarial/test_c2_emergent.py::test_adv_e2_03_same_week_retry_can_desynchronise_delta_and_views",
        "root_cause_hypothesis": "Carrying the prior weekly deltas forward is correct for 'a retry is not a new week', but the recomputed views are then not represented anywhere, so an intra-week information change becomes invisible.",
        "fixability": "NOT FIXED — requires deciding whether an intra-week revision is a new weekly-change event; overlaps decision-history semantics.",
        "owner": "REAL-SNAPSHOT-V1 owner / PR #133-#135",
        "status": "OPEN / DIAGNOSABILITY",
        "overlap_check": "producer.py not in PR #135/#132/#136, but the semantic overlaps #133's multi-week continuity.",
    },
    {
        "id": "ADV-P2-09",
        "severity": "P2",
        "invariant": "unit semantics are part of the source-identity contract",
        "title": "No unit cross-check between the provider contract and the series catalog",
        "exact_reproduction": [
            "config/series.yml declares US_NONFARM_PAYROLLS as thousands_persons",
            "FRED_MONITORING_CONTRACTS declares the same unit, but no code compares them; update_catalog_from_monitoring_rows only fills empty fields",
        ],
        "affected_path": "src/cross_asset/decision_support/monitoring_adapter.py, src/cross_asset/ingestion/monitoring.py, src/cross_asset/storage/catalog.py",
        "current_evidence": "static review; tests/adversarial/test_b1_identity_source.py covers identity but no unit case exists",
        "root_cause_hypothesis": "Monitoring factor transforms are unit-free (z-scores / trends), so a unit divergence has no decision impact today; it would matter for any level-based consumer.",
        "fixability": "NOT FIXED — no authority currently defines a machine-checkable unit contract for the monitoring lane.",
        "owner": "PROVIDER-CALENDAR-V1 owner (ONLINE-DEV-B)",
        "status": "OPEN / DIAGNOSABILITY",
        "overlap_check": "no overlap with PR #135/#132/#136.",
    },
    {
        "id": "ADV-GAP-01",
        "severity": "P2",
        "invariant": "decision history must exist for the product",
        "title": "No history-enumeration or current/prior diff surface on baseline main",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b6_snapshot_api.py -k b6_15",
            "SnapshotStore exposes only load/load_latest/persist",
        ],
        "affected_path": "src/cross_asset/decision_support/serving.py",
        "current_evidence": "tests/adversarial/test_b6_snapshot_api.py::test_adv_b6_15_history_and_diff_surfaces_are_absent_on_current_main",
        "root_cause_hypothesis": "Intentionally unmerged: PR #135 implements it.",
        "fixability": "NOT FIXED BY DESIGN — dedicated adjacent WIP.",
        "owner": "PR #135 / issue #133",
        "status": "GAP / ADJACENT-WIP",
        "overlap_check": "explicit non-overlap rule for this task.",
    },
    {
        "id": "ADV-GAP-02",
        "severity": "P2",
        "invariant": "lookback/source changes must stay comparable",
        "title": "Weekly semantic-comparability gate absent on baseline main",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b7_weekly_lane.py -k b7_12",
            "cross_asset.research.weekly_core has no source/semantic comparability gate",
        ],
        "affected_path": "src/cross_asset/research/weekly_core.py",
        "current_evidence": "tests/adversarial/test_b7_weekly_lane.py::test_adv_b7_12_weekly_comparability_gate_is_owned_by_131_132",
        "root_cause_hypothesis": "Intentionally unmerged: PR #132 implements it.",
        "fixability": "NOT FIXED BY DESIGN — dedicated adjacent WIP.",
        "owner": "PR #132 / issue #131",
        "status": "GAP / ADJACENT-WIP",
        "overlap_check": "explicit non-overlap rule for this task.",
    },
    {
        "id": "ADV-GAP-03",
        "severity": "P2",
        "invariant": "native runtime behaviour needs native evidence",
        "title": "Windows launcher / process-ownership scenarios not exercisable in this window",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b8_runtime_boundary.py -k b8_07",
            "launcher/ and START_MACRO_WORKBENCH.cmd are absent from baseline main",
        ],
        "affected_path": "PR #136 files",
        "current_evidence": "tests/adversarial/test_b8_runtime_boundary.py::test_adv_b8_07_native_windows_process_semantics_are_not_exercised_here",
        "root_cause_hypothesis": "PR #136 is the owner of native process proof; CI/Linux cannot prove Windows process semantics.",
        "fixability": "NOT FIXED BY DESIGN — EXTERNAL_EVIDENCE.",
        "owner": "PR #136 / issue #134",
        "status": "NOT_EXERCISED",
        "overlap_check": "explicit non-overlap rule for this task.",
    },
    {
        "id": "ADV-GAP-04",
        "severity": "NONE",
        "invariant": "no-Wind window must be explicit",
        "title": "Wind / iFinD / Tushare / CN proprietary identity lanes not exercised",
        "exact_reproduction": [
            "python -m pytest tests/adversarial/test_b1_identity_source.py -k b1_12",
            "config/sources.yml keeps wind/ifind/tushare disabled",
        ],
        "affected_path": "config/sources.yml, config/wind_canonical_mapping.yml",
        "current_evidence": "tests/adversarial/test_b1_identity_source.py::test_adv_b1_12_wind_only_identity_is_not_exercisable_in_this_window; tests/adversarial/test_b3_freshness_calendar.py honours the same limit",
        "root_cause_hypothesis": "Hard environment assumption of this dispatch window.",
        "fixability": "NOT APPLICABLE — must remain NOT_EXERCISED/BLOCKED.",
        "owner": "LOCAL-DEV-A / issue #93 (only when real files exist)",
        "status": "NOT_EXERCISED / NO-WIND",
        "overlap_check": "no code or config was changed to manufacture Wind-equivalent data.",
    },
]


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #


def render_matrix_md(rows: list[dict]) -> str:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
    layers: dict[str, int] = {}
    for row in rows:
        layers[row["layer"]] = layers.get(row["layer"], 0) + 1

    lines = [
        "# ADVERSARIAL MATRIX — ADVERSARIAL-E2E-VALIDATION-V1",
        "",
        f"- Owner lane: `{OWNER_LANE}`",
        f"- Baseline main: `{BASELINE_MAIN}`",
        f"- Total cases: **{len(rows)}**",
        f"- Status counts: {json.dumps(counts, sort_keys=True)}",
        f"- Per-layer counts: {json.dumps(layers, sort_keys=True)}",
        "- Environment: NO WIND / NO WindPy / no proprietary local files; such cells are NOT_EXERCISED or BLOCKED.",
        "",
        "Status vocabulary: `PASS` (invariant holds), `FAIL_FIXED` (violated on baseline, narrow fix shipped here),",
        "`FAIL_BLOCKER` (violated, recorded in the ledger), `GAP_ADJACENT_WIP` (absent by design, owned by",
        "#131/#132/#133/#134), `BLOCKED_POLICY` (requires a product decision), `NOT_EXERCISED` (no-Wind).",
        "",
        "| Case | Layer | Invariant | Expected | Observed | Status | Severity | Fix owner | Evidence |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            "| {case_id} | {layer} | {invariant} | {expected} | {observed} | **{status}** | {severity} | {fix_owner} | `{evidence}` |".format(
                **row
            )
        )
    lines.append("")
    return "\n".join(lines)


def render_ledger_md(items: list[dict]) -> str:
    lines = [
        "# BLOCKER LEDGER — ADVERSARIAL-E2E-VALIDATION-V1",
        "",
        f"- Owner lane: `{OWNER_LANE}`",
        f"- Baseline main: `{BASELINE_MAIN}`",
        f"- Items: **{len(items)}**",
        "- Severity: P0 fabricates/overwrites authority or crosses lanes; P1 misstates data/decision/history or breaks",
        "  normal use; P2 diagnosability/maintenance gap without current decision corruption.",
        "- No severity was inflated to consume work: no P0 was found by this window.",
        "",
    ]
    for item in items:
        lines.extend(
            [
                f"## {item['id']} — {item['title']}",
                "",
                f"- **Severity:** {item['severity']}",
                f"- **Invariant:** {item['invariant']}",
                f"- **Affected path:** `{item['affected_path']}`",
                f"- **Owner:** {item['owner']}",
                f"- **Status:** {item['status']}",
                f"- **Fixability:** {item['fixability']}",
                f"- **Overlap check:** {item['overlap_check']}",
                "",
                "**Exact reproduction**",
                "",
                "```text",
                *item["exact_reproduction"],
                "```",
                "",
                f"**Current evidence:** {item['current_evidence']}",
                "",
                f"**Root-cause hypothesis:** {item['root_cause_hypothesis']}",
                "",
            ]
        )
    return "\n".join(lines)


def render_dependency_md(payload: dict) -> str:
    lines = [
        "# DEPENDENCY MAP — ADVERSARIAL-E2E-VALIDATION-V1",
        "",
        f"- Owner lane: `{payload['owner_lane']}`",
        f"- Baseline main: `{payload['baseline_main']}`",
        "- Environment: NO WIND / NO WindPy / no proprietary local files.",
        "",
        "## Target chain",
        "",
        "```text",
        " -> ".join(payload["target_chain"]),
        "```",
        "",
        "## Components",
        "",
        "| Authority | Role | Inputs | Outputs | Persisted identity | Time semantics | Failure semantics | Formal/monitoring boundary | Existing coverage |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for item in payload["components"]:
        lines.append(
            "| `{authority}` | {role} | {inputs} | {outputs} | {persisted_identity} | {time_semantics} | {failure_semantics} | {formal_monitoring_boundary} | {existing_coverage} |".format(
                **item
            )
        )
    lines.extend(["", "## Adjacent WIP boundaries", "", "| PR | Issue | Title | Files | Rule |", "|---|---|---|---|---|"])
    for item in payload["adjacent_wip_boundaries"]:
        lines.append(
            f"| #{item['pr']} | #{item['issue']} | {item['title']} | {', '.join('`' + f + '`' for f in item['files'])} | {item['rule']} |"
        )
    lines.extend(
        [
            "",
            "## Hard environment assumption",
            "",
            "```json",
            json.dumps(payload["hard_environment_assumption"], indent=2, sort_keys=True),
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    (HERE / "DEPENDENCY_MAP.json").write_text(
        json.dumps(DEPENDENCY_MAP, indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )
    (HERE / "DEPENDENCY_MAP.md").write_text(
        render_dependency_md(DEPENDENCY_MAP), encoding="utf-8"
    )
    (HERE / "ADVERSARIAL_MATRIX.json").write_text(
        json.dumps(
            {
                "schema": "cross_asset.adversarial_e2e.matrix.v1",
                "task": TASK,
                "owner_lane": OWNER_LANE,
                "baseline_main": BASELINE_MAIN,
                "no_wind_window": True,
                "case_count": len(MATRIX),
                "cases": MATRIX,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (HERE / "ADVERSARIAL_MATRIX.md").write_text(render_matrix_md(MATRIX), encoding="utf-8")
    (HERE / "BLOCKER_LEDGER.json").write_text(
        json.dumps(
            {
                "schema": "cross_asset.adversarial_e2e.blocker_ledger.v1",
                "task": TASK,
                "owner_lane": OWNER_LANE,
                "baseline_main": BASELINE_MAIN,
                "item_count": len(LEDGER),
                "items": LEDGER,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (HERE / "BLOCKER_LEDGER.md").write_text(render_ledger_md(LEDGER), encoding="utf-8")
    print(f"cases={len(MATRIX)} ledger_items={len(LEDGER)}")


if __name__ == "__main__":
    main()
