"""Decision Support v2 core (Issue #114).

Pure/config-driven backend product foundation for the Macro Workbench:
DashboardSnapshotV0 contract, horizon model, four-surface weekly semantics,
V1 factor taxonomy, interpretable regime V0, and rule-driven asset gates.
"""

from .asset_rules import (
    AssetGateResult,
    GateBlocker,
    MacroBasis,
    build_asset_gate,
)
from .climate import (
    derive_climate_components,
    derive_investment_climate,
    derive_macro_climate,
)
from .enums import (
    AssetTarget,
    CauseTag,
    DataHealthStatus,
    EvidenceLane,
    GrowthState,
    HorizonClass,
    InflationState,
    InformationSetStatus,
    MarketConfirmation,
    MarketDeltaUnit,
    MarketMetricClass,
    QuadrantLabel,
    ReleaseEventType,
    SurpriseMethod,
)
from .fixtures import MODEL_VERSION, build_benign_snapshot, build_tightening_snapshot
from .horizon import (
    HorizonAggregate,
    HorizonMixingError,
    SubfactorScore,
    aggregate_cluster_horizon,
    aggregate_horizon,
    separate_by_horizon,
)
from .regime import (
    RegimeEngine,
    RegimeInsufficientDataError,
    evaluate_lens_disagreement,
)
from .snapshot import (
    AssetViewV0,
    ClimateComponent,
    ClimateState,
    ClusterView,
    CrossAssetPulse,
    DashboardSnapshotV0,
    DataHealthSummary,
    ExecutiveBrief,
    RegimeState,
    SnapshotMetadata,
    WeeklyChange,
)
from .taxonomy import (
    CANONICAL_FAMILIES,
    AssetRuleSpec,
    DecisionSupportConfig,
    SubfactorSpec,
    load_taxonomy,
)
from .weekly import (
    AssetStanceChange,
    AssetViewDelta,
    FactorStateChange,
    InformationSetDelta,
    MacroStateDelta,
    MarketConditionDelta,
    MarketMove,
    ReleaseEvent,
    SurpriseMetadata,
    SyntheticMovementError,
    build_information_set_delta,
    build_macro_state_delta,
    build_market_condition_delta,
    build_market_move,
)

__all__ = [
    "CANONICAL_FAMILIES",
    "MODEL_VERSION",
    "AssetGateResult",
    "AssetRuleSpec",
    "AssetStanceChange",
    "AssetTarget",
    "AssetViewDelta",
    "AssetViewV0",
    "CauseTag",
    "ClimateComponent",
    "ClimateState",
    "ClusterView",
    "CrossAssetPulse",
    "DashboardSnapshotV0",
    "DataHealthStatus",
    "DataHealthSummary",
    "DecisionSupportConfig",
    "EvidenceLane",
    "ExecutiveBrief",
    "FactorStateChange",
    "GateBlocker",
    "GrowthState",
    "HorizonAggregate",
    "HorizonClass",
    "HorizonMixingError",
    "InflationState",
    "InformationSetDelta",
    "InformationSetStatus",
    "MacroBasis",
    "MacroStateDelta",
    "MarketConditionDelta",
    "MarketConfirmation",
    "MarketDeltaUnit",
    "MarketMetricClass",
    "MarketMove",
    "QuadrantLabel",
    "RegimeEngine",
    "RegimeInsufficientDataError",
    "RegimeState",
    "ReleaseEvent",
    "ReleaseEventType",
    "SnapshotMetadata",
    "SubfactorScore",
    "SubfactorSpec",
    "SurpriseMetadata",
    "SurpriseMethod",
    "SyntheticMovementError",
    "WeeklyChange",
    "aggregate_cluster_horizon",
    "aggregate_horizon",
    "build_asset_gate",
    "build_benign_snapshot",
    "build_information_set_delta",
    "build_macro_state_delta",
    "build_market_condition_delta",
    "build_market_move",
    "build_tightening_snapshot",
    "derive_climate_components",
    "derive_investment_climate",
    "derive_macro_climate",
    "evaluate_lens_disagreement",
    "load_taxonomy",
    "separate_by_horizon",
]
